### ISSUE TITLE
Let demo page hosting by GitHub

### ISSUE THREAD

**Issue by denny0223** [Augus/ngAnimate#2]
[GitHub Pages](http://pages.github.com/) is a good idea to publish your demo page.

Here is [manual](https://help.github.com/articles/creating-project-pages-manually).

Just create a new branch named `gh-pages`, than you can access [http://augus.github.io/ngAnimate](http://augus.github.io/ngAnimate) to see your demo page.

Demo page on Dropbox is OK, but if someday remove files, need clone this project to try, recommend you use GitHub Pages.

**Comment by Augus** [comment]
Ok denny, demo link is change to http://augus.github.io/ngAnimate/ now.

**Comment by rschiang** [comment]
A brief reworking of the instructions above.

# Host demo page on GitHub

GitHub Pages is a good idea to publish your demo page.

Here is the [manual](https://help.github.com/articles/creating-project-pages-manually).

Just create a new branch named `gh-pages`, then you can access `https://augus.github.io/ngAnimate` to see your demo page.

Presenting pages on Dropbox is OK, but if they were removed someday, others would need to clone this project to try out. Recommend you use GitHub Pages.
